### ISSUE TITLE
voice input has problems

### ISSUE THREAD

**Issue by mschneider82** [olivia-ai/olivia-ai.org#171]
Hi, It seems the Speech-to-text has problems. When i goto https://olivia-ai.org/chat it also says "en-GB voice loaded." instead of de-DE, there are some javascript errors on console too:

```
Error during service worker registration: TypeError: Failed to register a ServiceWorker for scope ('https://olivia-ai.org/') with script ('https://olivia-ai.org/service-worker.js'): ServiceWorker script evaluation failed
```

**Comment by hugolgst** [comment]
Which navigator are you using?

**Comment by mschneider82** [comment]
chrome linux

**Comment by mschneider82** [comment]
on my android phone the speech input also does not work (also not in english)

**Comment by hugolgst** [comment]
It is working perfectly for me

**Comment by mschneider82** [comment]
now the speed input works, but it still selects an english voice for the german language so the spelling is not correct. did i missed something?

**Comment by hugolgst** [comment]
Maybe your chrome does not include the german voice?
Try to do `speechSynthesis.getVoices()` in your console and see if the voice is present or not

**Comment by mschneider82** [comment]
ah, yes on android the voice "anna" is working fine. In my chrome it says

```
default: true
lang: "de-DE"
localService: false
name: "Google Deutsch"
voiceURI: "Google Deutsch"
```

**Comment by hugolgst** [comment]
Anna does not exist on your chrome?

**Comment by mschneider82** [comment]
No it just has voices with prefix "Google "

**Comment by hugolgst** [comment]
Okay, thanks for these details I am going to resolve that.

**Comment by hugolgst** [comment]
It should work perfectly

**Comment by mschneider82** [comment]
works thanks
